env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 3
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-var:
    - error
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  object-shorthand:
    - error
  quote-props:
    - error
  no-unused-vars:
    - warn
  no-undef:
    - warn
