env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 3
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - warn
    - never
  # TURN ON these two checks when development begins
  no-unused-vars:
    - warn
  no-undef:
    - warn
